config/routes.rb
GrStatus::Application.routes.draw do
  match '/', to: redirect('/dashboard')
  match 'dashboard' => 'dashboard#index'
  match 'auth/:provider/callback', to: 'sessions#create', :as => :login
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'
  resources :web_sites, :clients

  namespace :admin do
    resources :clients do
      collection { post :sort }
    end
    resources :web_sites, :only => [] do
      collection { post :sort }
    end
    resources :google_analytics, :only => [:index, :show], :defaults => {:format => 'json'}, :constraints => {:format => 'json'}
    resources :github, :only => [:index], :defaults => {:format => 'json'}, :constraints => {:format => 'json'}
  end
  match 'admin/github/*id' => 'admin/github#show'

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @clients = Client.includes(:web_sites).order("sort_order").all
  end
end

app/views/dashboard/index.html.erb
<div class="gr_logo">
	<img src="icons/gr_logo.png">
</div>
<%if current_user%>
	<div class='edit_button'>
		<a class='btn btn-primary' href ="<%= admin_clients_path %>">Edit</a>
	</div>
<% end %>
<div class="container-fluid">		
<% @clients.each_slice(2) do |clients| %>
	<div class="row-fluid">
		<% clients.each do |client| %>
			<div class="span6">
				<div class="media showoff client_small">
					<b><a class="client_title" href='<%= client_path(client) %>'><%= client.name %></a></b>
					<div class="client_logo"><img width='80' src="<%= client.logo_url %>"></div>
					<div class="media-body scrollable">
						<% client.web_sites.order("sort_order").each do |website| %>
							<% status = find_status(website) %>
							<% up = status && /OK/.match(status['service_status']) %>
							<!-- These are the websites and their labels -->
							<div class="row-fluid webline">
								<span>
									<a href="<%= website.url %>"><%= website.host.to_s.gsub(/^www\./,'') %><%= website.path %></a>
								</span>
								<!-- These are the charts created using the smallchart function -->
								<span class="pull-right">
									<% if stuff=find_performance_data(website, 'time') %>
										<div id="chart_<%= h(website.url) %>" class="smallchart"></div>
										<script type="text/javascript">
											$(function () {
			    								$(document).ready(function() {
			        								smallchart("chart_<%= h(website.url) %>", 
			        									<%= stuff.to_json.html_safe %>
			        								);
			    								});
											});
										</script>
									<% end %>
								</span>
								<span class="light pull-right">
									<% if status %>
										<% if up  %>
											<% status_output = HTMLEntities.new.decode(status['service_plugin_output']) %>
											<% time_match = /([.0-9]+) second/.match(status_output) %>
											<span class="label label-success"><%= status['service_status'] %> - <%= (time_match[1].to_f*1000).to_i %>ms</span>
										<% elsif /CRITICAL/.match(status['service_status'])%>
											<span class="label label-important"><%= status['service_status'] %> for<%= " #{status['service_state_duration']}".gsub(/ 0(d|h|m|s)/, '') %></span>
										<% else %>
											<span class="label label-default"><%= status['service_status'] %></span>
										<% end %>
									<% else %>
										<span class="label label-warning">Not Monitored</span>
									<% end %>
								</span>
							</div>
						<% end %>
					</div>
				</div>
			</div>
		<% end %>
	</div>
<% end %>
</div>