config/routes.rb
GrStatus::Application.routes.draw do
  match '/', to: redirect('/dashboard')
  match 'dashboard' => 'dashboard#index'
  match 'auth/:provider/callback', to: 'sessions#create', :as => :login
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'
  resources :web_sites, :clients

  namespace :admin do
    resources :clients do
      collection { post :sort }
    end
    resources :web_sites, :only => [] do
      collection { post :sort }
    end
    resources :google_analytics, :only => [:index, :show], :defaults => {:format => 'json'}, :constraints => {:format => 'json'}
    resources :github, :only => [:index], :defaults => {:format => 'json'}, :constraints => {:format => 'json'}
  end
  match 'admin/github/*id' => 'admin/github#show'

end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :logo_url, :name, :web_sites_attributes, :description, :harvest_client_id, :sort_order

  validates :name, :presence => true, :uniqueness=>true

  has_many :web_sites, :dependent=>:destroy, :inverse_of=>:client

  accepts_nested_attributes_for :web_sites, :allow_destroy => true, 
    :reject_if => proc { |attributes| attributes['url'].blank? }
end

app/controllers/admin/clients_controller.rb
class Admin::ClientsController < Admin::BaseController
  def index
    @clients = Client.order("sort_order")
  end

  def show
    redirect_to :action=>:edit
  end
  
  def edit
  	@client=Client.find(params[:id])
    @client.web_sites.build
  end

  def update
  	@client=Client.find(params[:id])
  	if @client.update_attributes(params[:client])
      flash[:notice] = "Changes saved."
      redirect_to :action=>:edit
    else
    	render :action => :edit
    end
  end

  def sort
    params[:client].each_with_index do |id, index|
      Client.update_all({sort_order: index+1}, {id: id})
    end
    render nothing: true
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def show
  	@client=Client.find(params[:id])
  end
end

app/views/admin/clients/edit.html.erb
<h2>Client Edit Form</h2>
<%= simple_form_for [:admin, @client] do |f| %>
  <div class='row client_edit'>
    <div class='span4'>
      <%= f.input :name %>
      <br>
      <%= f.input :logo_url %>
    </div>
    <div class='span8'>
      <%= f.input :description, as: :text, :input_html => { :rows => 6 } %>
    </div>
  </div>
  <h3>Websites listed for this client</h3>
  <div id="web_site_list" data-update-url="<%= sort_admin_web_sites_path %>">
    <%= f.simple_fields_for :web_sites, f.object.web_sites.order("sort_order") do |sf| %>
      <div class='row website_edit' id="website_<%= sf.object.id %>">
        <span class="handle">[drag this to change order]</span>
        <div class='span3'>
          <%= sf.input :url, :class => "form_field" %>
        </div>
        <div class='span3'>
          <%= sf.input :ga_profile_id, :as => :select2, :input_html => {:id => "ga_#{sf.object.id}", :class => "form_field"}, :select2 => {:ajax=>{:url=>admin_google_analytics_path(:format=>'json'), :init_url => "/admin/google_analytics/"}} %>
        </div>
        <div class='span3'>
          <%= sf.input :git_path, :as => :select2, :input_html => {:id => "git_#{sf.object.id}", :class => "form_field"}, :select2 => {:ajax=>{:url=>admin_github_index_path(:format=>'json'), :init_url => "/admin/github/"}} %>
        </div>
        <div>
          <%= sf.check_box :_destroy %>
          <%= sf.label :_destroy, "Remove Website" %>
        </div> 
      </div>
    <% end %>
    <%= f.simple_fields_for :web_sites, f.object.web_sites.build do |sf| %>
      <div class='row'>
        <div class='span3'>
          <%= sf.input :url, :class => "form_field" %>
        </div>
        <div class='span3'>
          <%= sf.input :ga_profile_id, :as => :select2, :input_html => {:id => "ga_#{sf.object.id}", :class => "form_field"}, :select2 => {:ajax=>{:url=>admin_google_analytics_path(:format=>'json'), :init_url => "/admin/google_analytics/"}} %>
        </div>
        <div class='span3'>
          <%= sf.input :git_path, :as => :select2, :input_html => {:id => "git_#{sf.object.id}", :class => "form_field"}, :select2 => {:ajax=>{:url=>admin_github_index_path(:format=>'json'), :init_url => "/admin/github/"}} %>
        </div>
        <div>
          <p>Fill this in to add a new website to this client</p>
        </div>
      </div>
    <% end %>
  </div>
  <div class='row'>
    <div class='span12'>
      <%= f.button :submit %>
    </div>
  </div>
<% end %>

app/views/admin/clients/index.html.erb
<p>Click a client to edit that client.  Drag a client to reorder the clients.</p>
<ol id='client_list' data-update-url="<%= sort_admin_clients_path %>">
<% @clients.all.each do |client| %>
  <%= content_tag_for :li, client do %>
    <a href='<%= client_path(client) %>'><%= client.name %></a>
  <% end %>
<% end %>
</ol>